"""initial schema

Revision ID: 7d1117d0308d
Revises: 
Create Date: 2026-07-19 19:47:16.925333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1117d0308d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('selected_aircraft_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['selected_aircraft_id'], ['aircraft.id'], name='fk_selected_aircraft', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tail_number', sa.String(length=16), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('active_revision_id', sa.Integer(), nullable=True),
    sa.Column('allow_added_ballast_recommendations', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_revision_id'], ['aircraft_revisions.id'], name='fk_active_revision', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_user_id'), 'aircraft', ['user_id'], unique=False)
    op.create_table('aircraft_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('basic_empty_weight_lb', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('basic_empty_moment_lb_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('basic_empty_cg_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('max_ramp_weight_lb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_takeoff_weight_lb', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('max_landing_weight_lb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_zero_fuel_weight_lb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('known_useful_load_lb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('source_document_name', sa.String(length=128), nullable=True),
    sa.Column('source_document_date', sa.Date(), nullable=True),
    sa.Column('user_confirmation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aircraft_id', 'revision_number', name='uq_aircraft_revision_number')
    )
    op.create_index(op.f('ix_aircraft_revisions_aircraft_id'), 'aircraft_revisions', ['aircraft_id'], unique=False)
    op.create_table('cg_envelope_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_revision_id', sa.Integer(), nullable=False),
    sa.Column('weight_lb', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('forward_cg_limit_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('aft_cg_limit_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_revision_id'], ['aircraft_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cg_envelope_rows_aircraft_revision_id'), 'cg_envelope_rows', ['aircraft_revision_id'], unique=False)
    op.create_table('flight_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_revision_id', sa.Integer(), nullable=False),
    sa.Column('calculation_engine_version', sa.String(length=16), nullable=False),
    sa.Column('input_snapshot_json', sa.Text(), nullable=False),
    sa.Column('result_snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['aircraft_revision_id'], ['aircraft_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_calculations_aircraft_id'), 'flight_calculations', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flight_calculations_user_id'), 'flight_calculations', ['user_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_revision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('station_type', sa.Enum('FRONT_SEATS', 'REAR_SEATS', 'PASSENGER', 'BAGGAGE', 'FUEL', 'BALLAST', 'CUSTOM', name='stationtypeenum'), nullable=False),
    sa.Column('default_arm_in', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_adjustable_arm', sa.Boolean(), nullable=False),
    sa.Column('minimum_arm_in', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('maximum_arm_in', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('maximum_weight_lb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('maximum_volume_gal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('fuel_density_lb_per_gal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_revision_id'], ['aircraft_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_aircraft_revision_id'), 'stations', ['aircraft_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stations_aircraft_revision_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_flight_calculations_user_id'), table_name='flight_calculations')
    op.drop_index(op.f('ix_flight_calculations_aircraft_id'), table_name='flight_calculations')
    op.drop_table('flight_calculations')
    op.drop_index(op.f('ix_cg_envelope_rows_aircraft_revision_id'), table_name='cg_envelope_rows')
    op.drop_table('cg_envelope_rows')
    op.drop_index(op.f('ix_aircraft_revisions_aircraft_id'), table_name='aircraft_revisions')
    op.drop_table('aircraft_revisions')
    op.drop_index(op.f('ix_aircraft_user_id'), table_name='aircraft')
    op.drop_table('aircraft')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
