"""add fuel systems, temporary aircraft flag

Revision ID: beb0592006cc
Revises: 7d1117d0308d
Create Date: 2026-07-20 13:41:05.376606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb0592006cc'
down_revision: Union[str, None] = '7d1117d0308d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_revision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('input_mode', sa.Enum('SINGLE_ARM', 'UNKNOWN_SPLIT_RANGE', 'FIXED_ALLOCATION', name='fuelinputmodeenum'), nullable=False),
    sa.Column('usable_capacity_gal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_physical_capacity_gal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('fuel_density_lb_per_gal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_revision_id'], ['aircraft_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_systems_aircraft_revision_id'), 'fuel_systems', ['aircraft_revision_id'], unique=False)
    op.create_table('fuel_system_tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_system_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('usable_capacity_gal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('allocation_order', sa.Integer(), nullable=True),
    sa.Column('fixed_full_quantity_gal', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['fuel_system_id'], ['fuel_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_system_tanks_fuel_system_id'), 'fuel_system_tanks', ['fuel_system_id'], unique=False)
    op.create_index(op.f('ix_fuel_system_tanks_station_id'), 'fuel_system_tanks', ['station_id'], unique=False)
    op.add_column(
        'aircraft',
        sa.Column('is_temporary', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft', 'is_temporary')
    op.drop_index(op.f('ix_fuel_system_tanks_station_id'), table_name='fuel_system_tanks')
    op.drop_index(op.f('ix_fuel_system_tanks_fuel_system_id'), table_name='fuel_system_tanks')
    op.drop_table('fuel_system_tanks')
    op.drop_index(op.f('ix_fuel_systems_aircraft_revision_id'), table_name='fuel_systems')
    op.drop_table('fuel_systems')
    # ### end Alembic commands ###
